// <auto-generated />
using System;
using Fundsy_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundsy_backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Fundsy_backend.Models.Payment", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("Payment_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Payment_status_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Project_id")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("User_id")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("Project_id");

                    b.HasIndex("User_id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Fundsy_backend.Models.Project", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("Amount_Incurred")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Goal_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Payment_id")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Status_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("User_id")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Fundsy_backend.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role_id")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fundsy_backend.Models.Payment", b =>
                {
                    b.HasOne("Fundsy_backend.Models.Project", "Project")
                        .WithMany("Payments")
                        .HasForeignKey("Project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fundsy_backend.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fundsy_backend.Models.Project", b =>
                {
                    b.HasOne("Fundsy_backend.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fundsy_backend.Models.Project", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Fundsy_backend.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
